/**
 * API Route - Generate Chat Summary
 * 
 * This API route is designed to generate a concise summary of chat conversations using the OpenAI API.
 * It handles the reception of chat messages through a POST request, processes them to create a summary,
 * and returns the generated summary to the client. This functionality is essential for providing users
 * with a quick overview of their chat interactions.
 * 
 * Path: /api/generate-summary
 */

import { NextRequest, NextResponse } from 'next/server';
import OpenAI from "openai";

// Initialize the OpenAI client with the API key. This key is essential for authenticating 
// the requests with OpenAI's API services.
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export async function POST(request: NextRequest) {
  // Logging the start of the summary generation API call
  console.log('Starting the chat summary generation API call');

  try {
    // Extracting the chat content from the request body
    const { chat } = await request.json();

    // Check if the chat content is provided
    if (!chat) {
      console.error('No chat content found in the request');
      return NextResponse.json({ success: false, message: 'No chat content provided' }, { status: 400 });
    }

    // Log the receipt of the chat content
    console.log('Received chat content for summary generation');

    // Define the prompt for OpenAI to generate a summary
    const promptText = `Summarize the following user messages only, focusing on the essential points shared by the user. Exclude system or assistant responses, avoid unnecessary repetition, and write in clear, concise sentences. If user has not provided any message, just respond with "None". Emphasize actionable insights or unique feedback provided by the user. Write a short one and in simple English:\n\n${chat}\n\nSummary:`;

    // Log the chosen prompt
    console.log(`Using prompt: ${promptText}`);

    // Sending the chat content and prompt to OpenAI for summary generation
    console.log('Sending request to OpenAI for summary generation');
    const response = await openai.chat.completions.create({
      model: "gpt-4",
      messages: [
        {
          role: "system",
          content: "You are an assistant that summarizes chat conversations."
        },
        {
          role: "user",
          content: promptText
        }
      ],
      max_tokens: 150,
      temperature: 0.7,
    });

    // Log the response received from OpenAI
    console.log('Received response from OpenAI for summary generation');
    console.log('Response:', JSON.stringify(response, null, 2)); // Log the response for debugging

    // Extract and log the summary from the response
    const summary = response?.choices[0]?.message?.content?.trim();
    console.log('Generated Summary:', summary);

    // Check if summary was successfully generated
    if (!summary) {
      console.error('No summary generated by OpenAI');
      return NextResponse.json({ success: false, message: 'Failed to generate summary' }, { status: 500 });
    }

    // Return the generated summary in the response
    return NextResponse.json({ success: true, summary: summary });
  } catch (error: any) {
    // Log and handle any errors encountered during the request to OpenAI
    console.error('Error generating summary:', error);
    return NextResponse.json({ success: false, message: 'Error generating summary' }, { status: 500 });
  }
}